def design_card(a):
    #parts = a.split(',')
    aa, bb, cc, dd, ee, ff, d20, hh, ori, direc, d10, d100, crea, spe, prepo, ver, wea, confl, confl2, pla, sym, nou, fail, rac, trin, wdnd, dmg = a
    ff = int(ff)  # for round count
    print('D100', d100, '||', 'D20', d20, '||', 'D10', d10, '||', direc, '✓')
    print('Action Potential:', ff, alert, '|∆|', sym)
    print('|    Low odds:', cc)
    print('||       Odds:', bb)
    print('||| High Odds:', aa)
    print()
    print('Name:    ', dd, '||', 'phonetic')
    print('Creature:', rac, '||', crea)
    print('Weapon/tool:', wdnd, '||', wea)
    print('Status:', dmg)
    print()
    print('Orientation:', ori)
    print('Magic:', spe)
    print('Virtue | Flaw')
    print()
    print('<<Archetype>>', hh)
    print()
    print('-_-NARRATIVE ARC-_-')
    print('| Inciting Incident:')
    print()
    print('|| Conflict type:', confl, ' vs ', confl2)
    print()
    print('||| Consequence:', fail)
    print()
    print('| Location:', pla)
    print('|| Event', ver, ' ', prepo, ' ', nou)
    print()
    print('|', trin)
    print()
    ee = ee[:19]
    print('|| Card UUID:', ee)